services:
  db:
    image: postgres:16
    container_name: postgres_examen
    restart: always
    environment:
      POSTGRES_USER: user_pizza
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: laravel_pizza
    ports:
      - "5432:5432"